### PR TITLE
Feature: User Interface

### PR DESCRIPTION
**Pull request by OlukaDenis**
- Added the user interface logic

### CODE REVIEW

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Nice try :+1:
I like your efforts in implementing the required features for this milestone. However, we alot to work on before we can move on to the next milestone. Work on the suggested requests below.
- [ ] let game ask for player names
tic
- [ ] ask player to select from available moves
- [ ] display board after player move
- [ ] inform player if selected move is a winning move
- [ ] inform player if selected move is a draw move
- [ ] repeat all actions for next player's move

#### Please make the above changes and re-submit for another review.

### Martin Afani

**Comment by MarioDena** [comment]
Hello @whiz25 Like I told you on slack every action described is already present on our project. (Except for asking for a player's name that can't be found on the project requirements) We added more comments and better messages to make it more readable but the functionality was already there.

Cheers!

**Review by whiz25 — APPROVED** [review]
@OlukaDenis  and @MarioDena 
You can go ahead and merge. I wish you success in your upcoming projects.

### Martin Afani

**Comment by MarioDena** [comment]
@whiz25 Thank you!

**Pull request merged**
